### ISSUE TITLE
arm_example forward pass A option related confusion

### ISSUE THREAD

**Issue by cangozpi** [jmtomczak/intro_dgm#4]
Hi, 
As far as I understand, the option A in arm_example.ipynb refers to causality. Therefore A = True should signal that the model should not be taking the current time step t as an input. In the code implementation we discard the latest outpout of the convolution layer. I am confused by this since I thought we are supposed to discard the latest input. Are we not supposed to discard the latest (current time step) input to the model. In other words, for example, for the first convolution operation for t = 0,  are we not supposed to pad left (for 1D) with F-1 many elements, and feed into the first convolution the {(F-1), (F-2), ..., -1} time step elements to produce the output for t = 0 (initial) ?
```python
if self.A:
# Remember , we cannot be dependent on the current
component; therefore , the last element is removed .
return conv1d_out [:, :, : −1]
```
Sorry if I'm off. Just started to learn about these from the book. I will appreciate any help.

**Comment by jmtomczak** [comment]
Hi,
Thanks for the question!
It is just a matter of proper sizes. Please take a look at this line:
`self.padding = (kernel_size - 1) * dilation + A * 1`
You see, we add this extra padding. Why? Because we want to shift the input properly. And if we don't cut the last element out, the output would be too large.
I hope it helps!
