### ISSUE TITLE
The use of tanh in Euler forward sampling

### ISSUE THREAD

**Issue by cookbook-ms** [jmtomczak/intro_dgm#7]
I'm checking your most recent update on conditional flow matching and I see here you passed a tanh function after the Euler forward step. I wonder if there is any reason behind it? 

https://github.com/jmtomczak/intro_dgm/blob/main/sbgms/fm_example.ipynb
```[python]
    def sample(self,  batch_size=64):
        # Euler method
        # sample x_0 first
        x_t = self.sample_base(torch.empty(batch_size, self.D))
        
        # then go step-by-step to x_1 (data)        
        ts = torch.linspace(0., 1., self.T)
        delta_t = ts[1] - ts[0]
        
        for t in ts[1:]:
            t_embedding = self.time_embedding(torch.Tensor([t]))
            x_t = x_t + self.vnet(x_t + t_embedding) * delta_t
            # Stochastic Euler method
            if self.stochastic_euler:
                x_t = x_t + torch.randn_like(x_t) * delta_t
        
        x_final = torch.tanh(x_t) # **here's my question** 
        return x_final
```

**Comment by jmtomczak** [comment]
Hi!

The reason is very simple:
- I transform images to [-1,1].
- To ensure that pixel values are within the proper range, i.e., [-1,1], I apply tanh. Think of it as projecting |R to [-1,1].
Is it helpful? Yes.
Is it required? Not really (in the sense that flow matching does not need that).
I hope it helps!

Cheers,
Jakub
